### ISSUE TITLE
[Bug] Access token -1

### ISSUE THREAD

**Issue by ruben-janssens** [PatrickSt1991/Samsung-Jellyfin-Installer#187]
**Have you included the log files in this issue?**
- No
Logs show nothing intresting
  
**Which version of the application did you use?**  
v1.8.6.4-beta and previous versions

**Is your Samsung TV in developer mode?**  
- Yes  

**What Tizen version is your TV running?**  
8

**Operating system?**
- Linux

**Additional Context**  
After login I am always getting the following error:

<img width="585" height="440" alt="Image" src="https://github.com/user-attachments/assets/498cfd2f-4395-4a04-9efe-e13fb858221c" />

I have looked at other issues with the same error and attempted to follow the successful steps but to no avail.

**Comment by PatrickSt1991** [comment]
@ruben-janssens please attach all log files.

How old is the Samsung account you are using to sign in?

**Comment by ruben-janssens** [comment]
Below all logs files as requested. The Samsung Account is a few months old if I remember correctly.
If I check in developer mode the response does have all the fields mentioned in https://github.com/PatrickSt1991/Samsung-Jellyfin-Installer/blob/master/Jellyfin2Samsung-CrossOS/Models/SamsungAuth.cs

[process_apps_2025-12-08_17-42-32-519.log](https://github.com/user-attachments/files/24037621/process_apps_2025-12-08_17-42-32-519.log)
[process_capability_2025-12-08_17-42-32-612.log](https://github.com/user-attachments/files/24037626/process_capability_2025-12-08_17-42-32-612.log)
[process_capability_2025-12-08_17-42-32-624.log](https://github.com/user-attachments/files/24037620/process_capability_2025-12-08_17-42-32-624.log)
[process_devices_2025-12-08_17-42-32-547.log](https://github.com/user-attachments/files/24037623/process_devices_2025-12-08_17-42-32-547.log)
[process_diagnose_2025-12-08_17-42-31-202.log](https://github.com/user-attachments/files/24037625/process_diagnose_2025-12-08_17-42-31-202.log)
[process_disconnect_2025-12-08_17-42-38-304.log](https://github.com/user-attachments/files/24037622/process_disconnect_2025-12-08_17-42-38-304.log)
[process_x_2025-12-08_17-42-17-486.log](https://github.com/user-attachments/files/24037624/process_x_2025-12-08_17-42-17-486.log)
[process_x_2025-12-08_17-42-17-500.log](https://github.com/user-attachments/files/24037619/process_x_2025-12-08_17-42-17-500.log)

**Comment by PatrickSt1991** [comment]
@ruben-janssens do you see the webpage with the message that you can close it?

Cause that -1 means that the tool is missing the access token, I've seen it before with a bad Samsung account

**Comment by ruben-janssens** [comment]
I do get redirected `http://127.0.0.1:45031/signin/callback` with the content  `Login successful. You can close this window.`

**Comment by ruben-janssens** [comment]
FYI I have also enabled debug in the settings but seems like there aren't any more logs ?

**Comment by PatrickSt1991** [comment]
@ruben-janssens so apparently there is a bug in the package I'm using the create the certificates, this happens on some Linux OS, The check is now optional in the code and will only run for Windows.

I uploaded new packages in this release; [v1.8.6.4-beta](https://github.com/PatrickSt1991/Samsung-Jellyfin-Installer/releases/tag/v1.8.6.4-beta)

Your error should be fixed now.

**Comment by ruben-janssens** [comment]
I just downloaded the new package but sadly still the same error

**Comment by PatrickSt1991** [comment]
@ruben-janssens you are running this on linux? what OS and x64?

**Comment by ruben-janssens** [comment]
Correct, Debian 13 to be exact

**Comment by PatrickSt1991** [comment]
@ruben-janssens another build in the latest beta release [v1.8.6.4-beta](https://github.com/PatrickSt1991/Samsung-Jellyfin-Installer/releases/tag/v1.8.6.4-beta)

**Comment by ruben-janssens** [comment]
Still the same error, can I enable more logging somehow to help you along ?

**Comment by PatrickSt1991** [comment]
No unfortunally not.. when you press the gear icon what do you see here?

<img width="612" height="782" alt="Image" src="https://github.com/user-attachments/assets/decba843-77e9-44e3-a466-0664bfe36c45" />

**Comment by ruben-janssens** [comment]
I don't have the second Jelly2Sams certificate

<img width="617" height="788" alt="Image" src="https://github.com/user-attachments/assets/5ac0337a-a42b-4104-9b04-471bf7383a01" />

**Comment by PatrickSt1991** [comment]
@ruben-janssens okay yet another build in the latest release, last try for this evening

**Comment by ruben-janssens** [comment]
Sadly the same, we can continue tomorrow then

**Comment by PatrickSt1991** [comment]
Is it possible for you to capture that network traffic? Or maybe just create a HAR file?

Cause it seems you device is returning some different post data the i expect

**Comment by ruben-janssens** [comment]
You want a HAR from the POST to 127.0.0.1 ?

**Comment by ruben-janssens** [comment]
I just solved it ...
It was a wild guess from my side but I used a + (subaddressing) in my email and this somehow threw the error.
I updated my samsung account to not use the subaddress and it went through without a problem

**Comment by PatrickSt1991** [comment]
@ruben-janssens great news!

I just love that piece of sh*t Samsung software.. 

I'll fix it in my code to cover for their bug
